package types

// Problem is a structure for generating an object according to RFC 7807.
type Problem struct {
	Type     string   `json:"type" bson:"type"`         // An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).
	Title    string   `json:"title" bson:"title"`       // A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized).
	Status   int      `json:"status" bson:"status"`     // The HTTP status code generated by the origin server for this occurrence of the problem. 100–599.
	Detail   string   `json:"detail" bson:"detail"`     // A human readable explanation specific to this occurrence of the problem.
	Details  []string `json:"details" bson:"details"`   // A list of human readable explanation specific to this occurrence of the problem.
	Instance string   `json:"instance" bson:"instance"` // An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
}
